site_name: Mohan Mood | Computational Chemistry & AI
site_url: https://mohanmood.github.io/

extra_css:
  - stylesheets/freeze_title.css

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - About: about.md
  - Research: research.md
  - Publications: publications.md
  - Talks: talks.md
  - Gallery: gallery.md
  - News: news.md
  - Contact: contact.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed